language: elixir
sudo: false

elixir: '1.7.3'
otp_release: '21.3'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test
    - stage: check formatted
      script: mix format --check-formatted

notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - gazler@gmail.com
